package com.example.demo.entities;
// Generated Jun 6, 2024, 11:56:30 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.*;
/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "baobongda")
public class Comment implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String link;
	private String content;
	private String description;
	private Date pubDate;
	private Date created;
	private String image;
	private String title;
	private String category;
	private boolean status;

	public Comment() {
	}

	public Comment(Account account, String link, String content, String description, Date pubDate, Date created,
			String image, String title, String category, boolean status) {
		this.account = account;
		this.link = link;
		this.content = content;
		this.description = description;
		this.pubDate = pubDate;
		this.created = created;
		this.image = image;
		this.title = title;
		this.category = category;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountID", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "link", nullable = false, length = 65535)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pubDate", nullable = false, length = 10)
	public Date getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "image", nullable = false, length = 250)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "title", nullable = false, length = 65535)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "category", nullable = false, length = 65535)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
